Sondy/Models/SondyModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Text;
using System.Web;
using System.Xml;

namespace Sondy.Models
{
    public class Sonda
    {
        public string pytanie;
        public string data;
        public int liczbaOdpowiedzi;
        public List<string> odpowiedzi;
        public List<int> wyniki;

        public Sonda()
        {
            pytanie = "";
            data = "";
            liczbaOdpowiedzi = 0;
            odpowiedzi = new List<string>();
            wyniki = new List<int>();
        }
        public int getAllNoumberOfAnswers()
        {
            int suma = 0;
            foreach (var item in wyniki)
            {
                suma += item;
            }
            return suma;
        }
        public int percentOfTotal(int ilosc)
        {
            if(getAllNoumberOfAnswers()>0) return (int)(ilosc * 100 / getAllNoumberOfAnswers());
            return 0;
        }
    }

    public class Sondy
    {
        public List<Sonda> ListaSond;
        public Sonda AktualnaSonda;

        private int idAktualnejSondy;
        private string aktualnaData;  //    5.3.2012    

    public Sondy()
        {
            ListaSond = new List<Sonda>();
            aktualnaData = DateTime.Today.ToString("d"); //    5.3.2012
            parseFromFile();
            idAktualnejSondy = -1;
            AktualnaSonda = null;
            int i = 0;
            foreach (var SingleSonda in ListaSond)
            {                
                if(SingleSonda.data == aktualnaData) { idAktualnejSondy = i; break; }
                i++;
            }
            if (idAktualnejSondy >= 0) AktualnaSonda = ListaSond[idAktualnejSondy];

        }
        public void parseFromFile()
        {
                List<Sonda> listaSond = new List<Sonda>();
                string path = HttpContext.Current.Server.MapPath("~/Models/SondyXML.xml");
                //string path = @"c:\users\dkowalczyk\documents\visual studio 2015\Projects\Sondy\Sondy\Models\SondyXML.xml";
                string xmlString = File.ReadAllText(path);

                // Create an XmlReader
                using (XmlReader reader = XmlReader.Create(new StringReader(xmlString)))
                {
                    while (reader.ReadToFollowing("Sonda"))
                    {
                        Sonda singleSonda = new Sonda();
                        reader.ReadToFollowing("Pytanie");
                        singleSonda.pytanie = reader.ReadElementContentAsString();
                        reader.ReadToFollowing("Date");
                        singleSonda.data = reader.ReadElementContentAsString();
                        reader.ReadToFollowing("AnswerNo");
                        singleSonda.liczbaOdpowiedzi = reader.ReadElementContentAsInt();
                        for (int i = 0; i < singleSonda.liczbaOdpowiedzi; i++)
                        {
                            reader.ReadToFollowing("Answer");
                            singleSonda.odpowiedzi.Add(reader.ReadElementContentAsString());
                        }
                        reader.ReadToFollowing("Results");
                        for (int i = 0; i < singleSonda.liczbaOdpowiedzi; i++)
                        {
                            reader.ReadToFollowing("Result");
                            singleSonda.wyniki.Add(reader.ReadElementContentAsInt());
                        }
                        listaSond.Add(singleSonda);
                    }
                }
                ListaSond = listaSond;
        }
        public void parseToFile()
        {
                string output = "<Sondy>";
                for (int i = 0; i < ListaSond.Count; i++)
                {
                    output += "<Sonda>\n";
                    output += " <Pytanie>" + ListaSond[i].pytanie + "</Pytanie>\n";
                    output += " <Date>" + ListaSond[i].data + "</Date>\n";
                    output += " <AnswerNo>" + ListaSond[i].liczbaOdpowiedzi.ToString() + "</AnswerNo>\n";
                    output += "<Answers>\n";
                    for (int j = 0; j < ListaSond[i].liczbaOdpowiedzi; j++)
                    {
                        output += " <Answer>" + ListaSond[i].odpowiedzi[j] + "</Answer>\n";
                    }
                    output += "</Answers>\n";
                    output += "<Results>\n";
                    for (int j = 0; j < ListaSond[i].liczbaOdpowiedzi; j++)
                    {
                        output += " <Result>" + ListaSond[i].wyniki[j].ToString() + "</Result>\n";
                    }
                    output += "</Results>\n";
                    output += "</Sonda>\n";
                }
                output += "</Sondy>\n";
                System.IO.StreamWriter file = new System.IO.StreamWriter(HttpContext.Current.Server.MapPath("~/Models/SondyXML.xml"));
                file.WriteLine(output);
                file.Dispose();
        }

    }
}

Sondy/Controllers/SondyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sondy.Controllers
{
    public class SondyController : Controller
    {
        Sondy.Models.Sondy Obiekt = new Models.Sondy();
        HttpCookie SondaCookie;
        // GET: Sondy
        public ActionResult Index()
        {
            return View(Obiekt);
        }
        public ActionResult Summary()
        {
            return View(Obiekt);
        }

        [HttpGet]
        public ActionResult Post()
        {
            if (Request.Cookies["SondaCookie"] != null)
            {
                return View("Sorry");
            }
                return View(Obiekt);
        }

        public ActionResult Ajax()
        {
            if (Request.Cookies["SondaCookie"] != null)
            {
                return View("Sorry");
            }
            return View(Obiekt);
        }


        //[HttpPost]
        public ActionResult Answer()
        {
            SondaCookie = new HttpCookie("SondaCookie");
            SondaCookie.Expires = DateTime.Today.AddDays(1).AddHours(1);
            Response.Cookies.Add(SondaCookie);

            if (Request.Form["Radios"] == null) return View(Obiekt.AktualnaSonda);
            Obiekt.AktualnaSonda.wyniki[Int32.Parse(Request.Form["Radios"])]++;
            Obiekt.parseToFile();            
            return Redirect("Answer");
        }



        public string AjaxHandler(string radios)
        {
            SondaCookie = new HttpCookie("SondaCookie");
            SondaCookie.Expires = DateTime.Today.AddDays(1).AddHours(1);
            Response.Cookies.Add(SondaCookie);
            Obiekt.AktualnaSonda.wyniki[Int32.Parse(radios)]++;
            Obiekt.parseToFile();
            string output = "";
            int sumaWynikow = Obiekt.AktualnaSonda.getAllNoumberOfAnswers();
            for (int i = 0; i < Obiekt.AktualnaSonda.liczbaOdpowiedzi; i++)
            {
                int wynik = Obiekt.AktualnaSonda.wyniki[i];
                output += "<span>"+Obiekt.AktualnaSonda.odpowiedzi[i].ToString()+" ("+wynik.ToString()+" = "+ Obiekt.AktualnaSonda.percentOfTotal(wynik).ToString() + ")</span>";
                output += "<div class='progress'>";
                output += @"<div class='progress-bar' id='Answer_"+i.ToString()+"' role='progressbar' aria-valuenow='"+ Obiekt.AktualnaSonda.percentOfTotal(wynik).ToString()+"' aria-valuemin='0' aria-valuemax='100' style='width: "+ Obiekt.AktualnaSonda.percentOfTotal(wynik).ToString() + "%;'></div>";
                output += "</div></div>";
            }
            return output;
        }

    }
}

Sondy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona Główna", "Index", "Sondy")</li>
                    <li>@Html.ActionLink("Pierwszy(POST)", "Post", "Sondy")</li>
                    <li>@Html.ActionLink("Drugi(AJAX)", "Ajax", "Sondy")</li>
                    <li>@Html.ActionLink("Wyniki", "Summary", "Sondy")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Sonda Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryunob")
    @RenderSection("scripts", required: false)
</body>
</html>

Sondy/Views/Sondy/Ajax.cshtml
@model Sondy.Models.Sondy
@{
    ViewBag.Title = "Ajax";
}

<h2>Ajax</h2>

<script src="~/Scripts/jquery-3.1.1.js"></script>
@if (Model.AktualnaSonda != null)
{
<div id="AjaxDIV" class="show">




        <fieldset>
            <legend>@Model.AktualnaSonda.pytanie</legend>
            @for (int i = 0; i < Model.AktualnaSonda.odpowiedzi.Count; i++)
            {
                <div class="radio">
                    <label for="radios-0">
                        <input type="radio" name="radios" value="@i">
                        @Model.AktualnaSonda.odpowiedzi[i]
                    </label>
                </div>
            }

            <p>
                <input type="button" onclick="fire()" value="Wyslij" />
            </p>
        </fieldset>
    

</div>
<div id="JumboDIV"class="jumbotron hidden">
    <h1>@Model.AktualnaSonda.pytanie</h1>
    <div id="Wynik"></div>
</div>
}
    <script>

        function fire()
        {
            $.ajax(
                {
                    url: "/Sondy/AjaxHandler",
                    method: "POST",
                    data: {
                        radios: $(`input[name=radios]:checked`).val()
                    }
                }
            ).done(function (res) {
                console.log(res);
                $(`#AjaxDIV`).removeClass("show");
                $(`#AjaxDIV`).addClass("hidden");
                $(`#JumboDIV`).removeClass("hidden");
                $(`#Wynik`).append(res);
            })
            };

    </script>

Sondy/Views/Sondy/Answer.cshtml
@model Sondy.Models.Sonda
@{
    ViewBag.Title = "Answers";
}

<h2>Answers</h2>

<div class="jumbotron">
    <h1>@Model.pytanie</h1>
    @for (int i = 0; i < Model.liczbaOdpowiedzi; i++)
    {
        <span>@Model.odpowiedzi[i] (@Model.wyniki[i] = @Model.percentOfTotal(Model.wyniki[i])%)</span>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@Model.percentOfTotal(Model.wyniki[i])" aria-valuemin="0" aria-valuemax="100" style="width: @Model.percentOfTotal(Model.wyniki[i])%;">
                    
                </div>
            </div>
    }
</div>

Sondy/Views/Sondy/Index.cshtml
@model Sondy.Models.Sondy
@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-md-4">
        <h2>Dzisiejsza data:</h2>
        <p>
            @DateTime.Today.ToString("d")
        </p>
    </div>
    @if (Model.AktualnaSonda != null)
    {
    <div class="col-md-4">
        <h2>Dzisiejsza sonda</h2>
        <p>
            @Model.AktualnaSonda.pytanie
        </p>
    </div>
    <div class="col-md-4">
        <h2>Wybierz wersje sondy:</h2>
        @Html.ActionLink("Ver1 (POST)", "Post", "Sondy")
        <br />
        @Html.ActionLink("Ver2 (AJAX)", "Ajax", "Sondy")
    </div>
    }
    else
    {
        <div class="col-md-8">
            <h2>Przepraszamy, brak aktualnej sondy</h2>
        </div>
    }
</div>

Sondy/Views/Sondy/Post.cshtml
@model Sondy.Models.Sondy
@{
    ViewBag.Title = "Post";
}

<h2>Ver1 (POST)</h2>
@if (Model.AktualnaSonda != null)
{

    using (Html.BeginForm("Answer", "Sondy", FormMethod.Post))
    {
        <fieldset>
            <legend>@Model.AktualnaSonda.pytanie</legend>
            @for (int i = 0; i < Model.AktualnaSonda.odpowiedzi.Count; i++)
            {
                <div class="radio">
                    <label for="radios-0">
                        <input type="radio" name="radios" value="@i">
                        @Model.AktualnaSonda.odpowiedzi[i]
                    </label>
                </div>
            }

            <p>
                <input type="submit" value="Wyslij" />
            </p>
        </fieldset>
    }

}

Sondy/Views/Sondy/Sorry.cshtml
@{
    ViewBag.Title = "Sorry";
}

<h2>Przepraszamy ale dziś oddałeś już swój głos</h2>

Sondy/Views/Sondy/Summary.cshtml
@model Sondy.Models.Sondy
@{
    ViewBag.Title = "Summary";
}

<h2>Podsumowanie wynikow wszystkich ankiet</h2>

@foreach (var item in Model.ListaSond)
{

    <div class="jumbotron">
        <h1>@item.pytanie</h1>
        @for (int i = 0; i < item.liczbaOdpowiedzi; i++)
        {
            <span>@item.odpowiedzi[i] (@item.wyniki[i] = @item.percentOfTotal(item.wyniki[i])%)</span>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@item.percentOfTotal(item.wyniki[i])" aria-valuemin="0" aria-valuemax="100" style="width: @item.percentOfTotal(item.wyniki[i])%;">
                    
                </div>
            </div>
        }
    </div>
}